// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiSCvf6TKNnkEDwLjlBECuhPXF8FgsojY',
    appId: '1:132088450182:web:3429c2061eb1e8d8835507',
    messagingSenderId: '132088450182',
    projectId: 'news-app-3f5f8',
    authDomain: 'news-app-3f5f8.firebaseapp.com',
    storageBucket: 'news-app-3f5f8.appspot.com',
    measurementId: 'G-G21WLFJBDC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_WyY2fH7ZWFG1NgExlUHh85Ap-ms-oNU',
    appId: '1:132088450182:android:7c5e940b9cdf783b835507',
    messagingSenderId: '132088450182',
    projectId: 'news-app-3f5f8',
    storageBucket: 'news-app-3f5f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJpGMwEPNZx0AHIQjuql7O_2ITAyKIoZE',
    appId: '1:132088450182:ios:839f7019a530fdf4835507',
    messagingSenderId: '132088450182',
    projectId: 'news-app-3f5f8',
    storageBucket: 'news-app-3f5f8.appspot.com',
    iosBundleId: 'com.example.newsLastApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJpGMwEPNZx0AHIQjuql7O_2ITAyKIoZE',
    appId: '1:132088450182:ios:076702aa766e92e5835507',
    messagingSenderId: '132088450182',
    projectId: 'news-app-3f5f8',
    storageBucket: 'news-app-3f5f8.appspot.com',
    iosBundleId: 'com.example.newsLastApp.RunnerTests',
  );
}
